# Generated by Django 3.0.1 on 2019-12-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='List',
        ),
    ]
